In [5]:
import pandas as pd

import statbotics

sb = statbotics.Statbotics()

In [17]:
team_years = sb.get_team_years(year=2022)
team_years_df = pd.DataFrame(team_years)
team_years_df = team_years_df[team_years_df.elo_max > 0]

In [37]:
elo_df = team_years_df[["team", "name", "state", "country", "district", "elo_start", "elo_end", "elo_diff"]]

elo_df[elo_df.elo_end < 1900].sort_values(by="elo_diff", ascending=False)[:10]

,team,name,state,country,district,elo_start,elo_end,elo_diff
544,1771,North Gwinnett Robotics,GA,USA,pch,1661,1824.0,163.0
648,2135,Presentation Invasion,CA,USA,None,1491,1651.0,160.0
159,359,Hawaiian Kids,HI,USA,None,1676,1831.0,155.0
550,1787,Flying Circuits,OH,USA,None,1584,1723.0,139.0
27,70,More Martians,MI,USA,fim,1579,1717.0,138.0
93,201,The FEDS,MI,USA,fim,1531,1664.0,133.0
677,2200,MMRambotics,ON,Canada,ont,1707,1839.0,132.0
310,955,CV Robotics,OR,USA,pnw,1490,1619.0,129.0
990,3142,Aperture,NJ,USA,fma,1576,1702.0,126.0
53,118,Robonauts,TX,USA,fit,1758,1883.0,125.0

In [35]:
team_events_1 = sb.get_team_events(year=2022, week=1)
team_events_2 = sb.get_team_events(year=2022, week=2)

team_events_df_1 = pd.DataFrame(team_events_1)
team_events_df_2 = pd.DataFrame(team_events_2)

team_events_df_1 = team_events_df_1[team_events_df_1.elo_max > 0][["team", "team_name", "event", "state", "district", "elo_start", "elo_end", "wins", "losses", "ties"]]
team_events_df_2 = team_events_df_2[team_events_df_2.elo_max > 0][["team", "team_name", "event", "state", "district", "elo_start", "elo_end", "wins", "losses", "ties"]]

In [36]:
display(team_events_df_1[team_events_df_1.elo_end > team_events_df_1.elo_start].sort_values(by="elo_end", ascending=False)[:25])
display(team_events_df_2[team_events_df_2.elo_end > team_events_df_2.elo_start].sort_values(by="elo_end", ascending=False)[:25])

,team,team_name,event,state,district,elo_start,elo_end,wins,losses,ties
141,1678,Citrus Circuits,2022caph,CA,None,1798,2000,17,1,0
22,148,Robowranglers,2022txwac,TX,fit,1817,1954,18,0,0
258,2910,Jack in the Bot,2022wasno,WA,pnw,1828,1952,17,1,0
142,1690,Orbit,2022isde1,All,isr,1796,1947,17,1,0
25,179,Children of the Swamp,2022flwp,FL,None,1773,1874,17,1,0
3,27,Team RUSH,2022miket,MI,fim,1739,1853,16,1,1
311,3310,Black Hawk Robotics,2022txwac,TX,fit,1702,1846,17,1,0
195,2200,MMRambotics,2022on306,ON,ont,1766,1839,13,0,0
410,4414,HighTide,2022caph,CA,None,1694,1831,16,1,1
184,2168,Aluminum Falcons,2022flwp,FL,None,1778,1817,14,3,1
316,3357,COMETS,2022mifor,MI,fim,1695,1811,17,1,1
569,5895,Peddie Robotics,2022pahat,PA,fma,1652,1805,17,2,0
89,973,Greybots,2022caph,CA,None,1788,1801,12,7,0
713,7407,Wired Boars,2022nhgrs,NH,ne,1612,1796,18,0,0
484,5172,Gators,2022mndu2,MN,None,1776,1796,14,1,0
359,3847,Spectrum -△◅,2022txdri,TX,fit,1694,1794,16,2,0
517,5460,Strike Zone,2022miket,MI,fim,1781,1792,15,2,1
611,6328,Mechanical Advantage,2022nhgrs,NH,ne,1613,1769,17,1,0
123,1540,Flaming Chickens,2022orore,OR,pnw,1766,1767,13,5,0
194,2200,MMRambotics,2022on305,ON,ont,1707,1766,13,1,0
13,95,Grasshoppers,2022nhgrs,NH,ne,1695,1766,15,3,0
37,359,Hawaiian Kids,2022caph,CA,None,1676,1764,13,6,0
417,4488,Shockwave,2022orore,OR,pnw,1689,1760,15,3,0
4,33,Killer Bees,2022midet,MI,fim,1724,1758,17,2,0
65,624,CRyptonite,2022txwac,TX,fit,1674,1756,11,5,0

,team,team_name,event,state,district,elo_start,elo_end,wins,losses,ties
38,179,Children of the Swamp,2022flor,FL,None,1874,1929,15,0,0
461,4414,HighTide,2022cave,CA,None,1831,1890,17,0,0
26,118,Robonauts,2022txcha,TX,fit,1758,1883,18,0,0
366,3538,RoboJackets,2022miroc,MI,fim,1784,1883,17,1,0
121,987,HIGHROLLERS,2022caoc,CA,None,1773,1864,15,2,0
35,176,Aces High,2022ctwat,CT,ne,1739,1855,18,0,0
222,2046,Bear Metal,2022orwil,OR,pnw,1833,1836,16,4,0
186,1619,Up-A-Creek Robotics,2022okok,OK,None,1760,1831,16,0,0
74,359,Hawaiian Kids,2022cave,CA,None,1764,1831,16,1,0
357,3476,Code Orange,2022caoc,CA,None,1657,1828,15,1,1
496,4635,PrepaTec - Botbusters,2022mxmo,All,None,1678,1828,16,0,0
201,1771,North Gwinnett Robotics,2022gadal,GA,pch,1661,1824,17,1,0
15,67,The HOT Team,2022mimil,MI,fim,1735,1823,12,4,1
39,180,S.P.A.M.,2022flor,FL,None,1702,1815,15,0,0
287,2767,Stryke Force,2022misjo,MI,fim,1760,1813,18,1,0
473,4481,Team Rembrandts,2022flor,FL,None,1722,1799,11,3,0
413,4020,Cyber Tribe,2022scan,SC,None,1650,1789,16,2,0
177,1540,Flaming Chickens,2022orwil,OR,pnw,1767,1788,15,4,0
307,2990,Hotwire,2022orwil,OR,pnw,1721,1772,17,3,0
345,3339,BumbleB,2022isde2,All,isr,1694,1754,15,4,0
170,1506,Metal Muscle,2022miroc,MI,fim,1673,1754,15,3,0
28,133,B.E.R.T.,2022melew,ME,ne,1740,1754,13,3,0
268,2590,Nemesis,2022njfla,NJ,fma,1673,1746,14,4,0
52,230,Gaelhawks,2022ctwat,CT,ne,1674,1745,16,3,0
491,4613,Barker Redbacks,2022ausc,All,None,1708,1744,17,2,0